"""
Markdown exporter for human-readable vulnerability reports.

Creates formatted markdown reports for pentesters.
"""

from pathlib import Path
from datetime import datetime
from typing import List

from aegis_sast.core.models import ScanResult, Vulnerability, Severity


class MarkdownExporter:
    """Exports vulnerability reports in Markdown format."""
    
    def __init__(self, output_dir: Path):
        """
        Initialize Markdown exporter.
        
        Args:
            output_dir: Directory to save reports
        """
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def export(self, scan_result: ScanResult, filename: str = None) -> Path:
        """
        Export scan results to Markdown file.
        
        Args:
            scan_result: ScanResult object
            filename: Optional custom filename
            
        Returns:
            Path to exported file
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"aegis_sast_report_{timestamp}.md"
        
        output_path = self.output_dir / filename
        
        # Build markdown content
        content = self._generate_report(scan_result)
        
        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return output_path
    
    def _generate_report(self, scan_result: ScanResult) -> str:
        """Generate markdown report content."""
        lines = []
        
        # Header
        lines.append("# 🔒 Aegis-SAST Security Report\n")
        lines.append(f"**Target**: `{scan_result.target_path}`  ")
        lines.append(f"**Date**: {scan_result.start_time.strftime('%Y-%m-%d %H:%M:%S')}  ")
        lines.append(f"**Duration**: {scan_result.duration:.2f}s  ")
        lines.append(f"**Files Scanned**: {scan_result.files_scanned}\n")
        
        # Summary
        summary = self._get_summary_line(scan_result)
        lines.append(f"**Total Findings**: {scan_result.total_vulnerabilities} ({summary})\n")
        lines.append("---\n")
        
        # Group vulnerabilities by severity
        critical = [v for v in scan_result.vulnerabilities if v.severity == Severity.CRITICAL]
        high = [v for v in scan_result.vulnerabilities if v.severity == Severity.HIGH]
        medium = [v for v in scan_result.vulnerabilities if v.severity == Severity.MEDIUM]
        low = [v for v in scan_result.vulnerabilities if v.severity == Severity.LOW]
        
        # Critical vulnerabilities
        if critical:
            lines.append("## 🔴 Critical Vulnerabilities\n")
            for vuln in critical:
                lines.append(self._format_vulnerability(vuln))
                lines.append("---\n")
        
        # High vulnerabilities
        if high:
            lines.append("## 🟠 High Severity Vulnerabilities\n")
            for vuln in high:
                lines.append(self._format_vulnerability(vuln))
                lines.append("---\n")
        
        # Medium vulnerabilities
        if medium:
            lines.append("## 🟡 Medium Severity Vulnerabilities\n")
            for vuln in medium:
                lines.append(self._format_vulnerability(vuln))
                lines.append("---\n")
        
        # Low vulnerabilities
        if low:
            lines.append("## 🔵 Low Severity Vulnerabilities\n")
            for vuln in low:
                lines.append(self._format_vulnerability(vuln))
                lines.append("---\n")
        
        # Errors
        if scan_result.errors:
            lines.append("## ⚠️ Scan Errors\n")
            for error in scan_result.errors:
                lines.append(f"- `{error}`\n")
            lines.append("\n")
        
        # Footer
        lines.append("---\n")
        lines.append("*Generated by Aegis-SAST v1.0.0*\n")
        
        return "\n".join(lines)
    
    def _get_summary_line(self, scan_result: ScanResult) -> str:
        """Get one-line summary with emoji indicators."""
        parts = []
        
        if scan_result.critical_count > 0:
            parts.append(f"🔴 {scan_result.critical_count} Critical")
        
        if scan_result.high_count > 0:
            parts.append(f"🟠 {scan_result.high_count} High")
        
        if scan_result.medium_count > 0:
            parts.append(f"🟡 {scan_result.medium_count} Medium")
        
        if scan_result.low_count > 0:
            parts.append(f"🔵 {scan_result.low_count} Low")
        
        return " | ".join(parts) if parts else "No vulnerabilities found"
    
    def _format_vulnerability(self, vuln: Vulnerability) -> str:
        """Format single vulnerability as markdown."""
        lines = []
        
        lines.append(f"### {vuln.id}: {vuln.vuln_type.value} in `{Path(vuln.file_path).name}:{vuln.line_number}`\n")
        lines.append(f"**Type**: {vuln.vuln_type.value}  ")
        lines.append(f"**Severity**: {vuln.severity.value}  ")
        lines.append(f"**File**: `{vuln.file_path}`  ")
        lines.append(f"**Line**: {vuln.line_number}\n")
        
        # Dataflow
        lines.append("**Dataflow Path**:\n")
        path_summary = vuln.dataflow.get_path_summary()
        for i, step in enumerate(path_summary, 1):
            if "[SANITIZER]" in step:
                lines.append(f"{i}. 🛡️ {step}\n")
            elif i == 1:
                lines.append(f"{i}. 🚪 **SOURCE**: {step}\n")
            elif i == len(path_summary):
                lines.append(f"{i}. ⚠️ **SINK**: {step}\n")
            else:
                lines.append(f"{i}. {step}\n")
        
        lines.append("\n")
        
        # AI Verification
        if vuln.ai_verification:
            ai = vuln.ai_verification
            
            status_icon = "❌" if ai.is_vulnerable else "✅"
            confidence_pct = int(ai.confidence * 100)
            
            lines.append("**AI Analysis**:\n")
            lines.append(f"{status_icon} **{'Vulnerable' if ai.is_vulnerable else 'Not Vulnerable'}** (Confidence: {confidence_pct}%)\n\n")
            lines.append(f"**Explanation**: {ai.explanation}\n\n")
            lines.append(f"**Recommendation**: {ai.recommendation}\n\n")
            lines.append(f"*Model: {ai.model_used}*\n")
        
        lines.append("\n")
        
        return "\n".join(lines)
