"""Markdown exporter for human-readable vulnerability and triage reports."""

from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from aegis_sast.core.models import ScanResult, Severity, Vulnerability
from aegis_sast.triage.schema import TriageRecord


class MarkdownExporter:
    """Exports vulnerability reports in Markdown format."""

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export(
        self,
        scan_result: ScanResult,
        filename: str = None,
        triage_records: Optional[List[TriageRecord]] = None,
        workflow_metadata: Optional[Dict[str, object]] = None,
    ) -> Path:
        """Export scan results to a Markdown report file."""
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"aegis_sast_report_{timestamp}.md"

        output_path = self.output_dir / filename
        content = self._generate_report(scan_result, triage_records, workflow_metadata)

        with open(output_path, "w", encoding="utf-8") as file_handle:
            file_handle.write(content)

        return output_path

    def _generate_report(
        self,
        scan_result: ScanResult,
        triage_records: Optional[List[TriageRecord]] = None,
        workflow_metadata: Optional[Dict[str, object]] = None,
    ) -> str:
        """Generate Markdown report content."""
        lines = []

        lines.append("# Aegis-SAST Security Report\n")
        lines.append(f"**Target**: `{scan_result.target_path}`  ")
        lines.append(f"**Date**: {scan_result.start_time.strftime('%Y-%m-%d %H:%M:%S')}  ")
        lines.append(f"**Duration**: {scan_result.duration:.2f}s  ")
        lines.append(f"**Files Scanned**: {scan_result.files_scanned}\n")

        summary = self._get_summary_line(scan_result)
        lines.append(f"**Total Findings**: {scan_result.total_vulnerabilities} ({summary})\n")
        if triage_records:
            lines.append(f"**Triage Summary**: {self._get_triage_summary_line(triage_records)}\n")
        if workflow_metadata:
            lines.append(self._format_workflow_summary(workflow_metadata))
        lines.append("---\n")

        severity_groups = self._group_by_severity(scan_result, triage_records)
        headings = [
            ("critical", "## Critical Vulnerabilities\n"),
            ("high", "## High Severity Vulnerabilities\n"),
            ("medium", "## Medium Severity Vulnerabilities\n"),
            ("low", "## Low Severity Vulnerabilities\n"),
        ]

        for key, heading in headings:
            items = severity_groups[key]
            if not items:
                continue
            lines.append(heading)
            for item in items:
                lines.append(self._format_item(item))
                lines.append("---\n")

        if scan_result.errors:
            lines.append("## Scan Errors\n")
            for error in scan_result.errors:
                lines.append(f"- `{error}`\n")
            lines.append("\n")

        lines.append("---\n")
        lines.append("*Generated by Aegis-SAST v1.0.0*\n")
        return "\n".join(lines)

    @staticmethod
    def _format_workflow_summary(workflow_metadata: Dict[str, object]) -> str:
        """Render a compact workflow summary block."""
        lines = ["## Workflow Summary\n"]
        if workflow_metadata.get("scan_profile"):
            lines.append(f"- **Scan Profile**: `{workflow_metadata['scan_profile']}`\n")
        if workflow_metadata.get("framework_hints"):
            hints = ", ".join(workflow_metadata["framework_hints"])
            lines.append(f"- **Framework Hints**: {hints}\n")
        if workflow_metadata.get("knowledge_card_count") is not None:
            lines.append(
                f"- **Knowledge Cards Loaded**: {workflow_metadata['knowledge_card_count']}\n"
            )
        for key, label in [
            ("route_summary", "Route Summary"),
            ("auditor_summary", "Auditor Summary"),
            ("skeptic_summary", "Skeptic Summary"),
            ("judge_summary", "Judge Summary"),
        ]:
            value = workflow_metadata.get(key)
            if value:
                lines.append(f"- **{label}**: `{value}`\n")
        if workflow_metadata.get("deterministic_triage_summary"):
            lines.append(
                "- **Deterministic Triage**: "
                f"`{workflow_metadata['deterministic_triage_summary']}`\n"
            )
        if workflow_metadata.get("ai_triage_summary"):
            lines.append(
                "- **AI Triage Summary**: "
                f"`{workflow_metadata['ai_triage_summary']}`\n"
            )
        lines.append("\n")
        return "".join(lines)

    @staticmethod
    def _group_by_severity(
        scan_result: ScanResult,
        triage_records: Optional[List[TriageRecord]],
    ) -> dict:
        """Group either raw findings or triage records by severity."""
        if triage_records:
            return {
                "critical": [r for r in triage_records if r.finding.severity == Severity.CRITICAL],
                "high": [r for r in triage_records if r.finding.severity == Severity.HIGH],
                "medium": [r for r in triage_records if r.finding.severity == Severity.MEDIUM],
                "low": [r for r in triage_records if r.finding.severity == Severity.LOW],
            }

        return {
            "critical": [v for v in scan_result.vulnerabilities if v.severity == Severity.CRITICAL],
            "high": [v for v in scan_result.vulnerabilities if v.severity == Severity.HIGH],
            "medium": [v for v in scan_result.vulnerabilities if v.severity == Severity.MEDIUM],
            "low": [v for v in scan_result.vulnerabilities if v.severity == Severity.LOW],
        }

    @staticmethod
    def _get_summary_line(scan_result: ScanResult) -> str:
        """Get a one-line severity summary."""
        parts = []
        if scan_result.critical_count > 0:
            parts.append(f"{scan_result.critical_count} Critical")
        if scan_result.high_count > 0:
            parts.append(f"{scan_result.high_count} High")
        if scan_result.medium_count > 0:
            parts.append(f"{scan_result.medium_count} Medium")
        if scan_result.low_count > 0:
            parts.append(f"{scan_result.low_count} Low")
        return " | ".join(parts) if parts else "No vulnerabilities found"

    @staticmethod
    def _get_triage_summary_line(triage_records: List[TriageRecord]) -> str:
        """Get a one-line triage summary."""
        counts = {}
        for record in triage_records:
            status = record.decision.status.value
            counts[status] = counts.get(status, 0) + 1
        parts = [f"{status}: {count}" for status, count in counts.items()]
        return " | ".join(parts) if parts else "No triage data"

    def _format_item(self, item) -> str:
        """Format either a raw vulnerability or a triage record."""
        if isinstance(item, TriageRecord):
            return self._format_triage_record(item)
        return self._format_vulnerability(item)

    @staticmethod
    def _format_vulnerability(vuln: Vulnerability) -> str:
        """Format one raw vulnerability in Markdown."""
        lines = []
        lines.append(
            f"### {vuln.id}: {vuln.vuln_type.value} in "
            f"`{Path(vuln.file_path).name}:{vuln.line_number}`\n"
        )
        lines.append(f"**Type**: {vuln.vuln_type.value}  ")
        lines.append(f"**Severity**: {vuln.severity.value}  ")
        lines.append(f"**File**: `{vuln.file_path}`  ")
        lines.append(f"**Line**: {vuln.line_number}\n")

        lines.append("**Dataflow Path**:\n")
        for index, step in enumerate(vuln.dataflow.get_path_summary(), 1):
            lines.append(f"{index}. {step}\n")

        if vuln.ai_verification:
            ai = vuln.ai_verification
            lines.append("\n**AI Analysis**:\n")
            lines.append(
                f"- vulnerable: `{ai.is_vulnerable}`\n"
                f"- confidence: `{int(ai.confidence * 100)}%`\n"
                f"- explanation: {ai.explanation}\n"
                f"- recommendation: {ai.recommendation}\n"
                f"- model: `{ai.model_used}`\n"
            )

        lines.append("\n")
        return "\n".join(lines)

    @staticmethod
    def _format_triage_record(record: TriageRecord) -> str:
        """Format one triage record in Markdown."""
        finding = record.finding
        decision = record.decision
        lines = []

        lines.append(
            f"### {finding.id}: {finding.vulnerability_type} in "
            f"`{Path(finding.file_path).name}:{finding.line_number}`\n"
        )
        lines.append(f"**Type**: {finding.vulnerability_type}  ")
        lines.append(f"**Severity**: {finding.severity.value}  ")
        lines.append(f"**Triage Status**: {decision.status.value}  ")
        lines.append(f"**Confidence**: {int(decision.confidence * 100)}%  ")
        lines.append(f"**File**: `{finding.file_path}`  ")
        lines.append(f"**Line**: {finding.line_number}\n")

        lines.append("**Evidence Path**:\n")
        path_steps = [
            str(finding.evidence.source),
            *[str(step) for step in finding.evidence.intermediate_steps],
            *[
                f"[SANITIZER] {sanitizer.function_name} at {sanitizer.location}"
                for sanitizer in finding.evidence.sanitizers
            ],
            str(finding.evidence.sink),
        ]
        for index, step in enumerate(path_steps, 1):
            lines.append(f"{index}. {step}\n")

        evidence_summary = finding.evidence.summary
        graph_slice = evidence_summary.get("graph_slice", {})
        helper_count = graph_slice.get("local_helper_count", 0)
        lines.append(
            "\n**Evidence Summary**: "
            f"path_length={evidence_summary.get('path_length', 0)}, "
            f"intermediate_steps={evidence_summary.get('intermediate_step_count', 0)}, "
            f"sanitizers={evidence_summary.get('sanitizer_count', 0)}, "
            f"helpers={helper_count}\n"
        )

        graph_summary = finding.evidence.metadata.get("graph_summary")
        if graph_summary:
            lines.append(
                "\n**Graph Summary**: "
                f"nodes={graph_summary.get('node_count', 0)}, "
                f"cfg_edges={graph_summary.get('cfg_edge_count', 0)}, "
                f"dfg_edges={graph_summary.get('dfg_edge_count', 0)}\n"
            )

        local_callee_summaries = finding.evidence.metadata.get("local_callee_summaries")
        if local_callee_summaries:
            lines.append("\n**Local Helper Summaries**:\n")
            for summary in local_callee_summaries:
                params = ", ".join(summary.get("dependent_parameters", [])) or "none"
                lines.append(
                    "- "
                    f"{summary.get('function_name', 'unknown')} "
                    f"(call line {summary.get('call_site_line', '?')}), "
                    f"dependent params: {params}\n"
                )

        if finding.metadata.get("knowledge_card_ids"):
            joined = ", ".join(finding.metadata["knowledge_card_ids"])
            lines.append(f"\n**Knowledge Cards**: {joined}\n")

        lines.append(f"\n**Decision**: {decision.explanation}\n")
        if decision.recommendation:
            lines.append(f"\n**Recommendation**: {decision.recommendation}\n")
        if decision.reason_codes:
            lines.append(
                "\n**Reason Codes**: "
                + ", ".join(decision.reason_codes)
                + "\n"
            )
        lines.append(
            "\n**Manual Review Required**: "
            f"{'yes' if decision.manual_review_required else 'no'}\n"
        )

        route = decision.metadata.get("workflow_route")
        if route:
            lines.append(f"\n**Suggested Route**: {' -> '.join(route['steps'])}\n")

        reviews = MarkdownExporter._collect_agent_reviews(record)
        if any(reviews.values()):
            lines.append("\n**Agent Reviews**:\n")
            if reviews["auditor_review"]:
                auditor = reviews["auditor_review"]
                lines.append(f"- auditor: {auditor.get('summary', 'n/a')}\n")
            if reviews["skeptic_review"]:
                skeptic = reviews["skeptic_review"]
                lines.append(f"- skeptic: {skeptic.get('summary', 'n/a')}\n")
            if reviews["judge_review"]:
                judge = reviews["judge_review"]
                lines.append(f"- judge: {judge.get('summary', 'n/a')}\n")

        if decision.evidence_notes:
            lines.append("\n**Evidence Notes**:\n")
            for note in decision.evidence_notes:
                lines.append(f"- {note}\n")

        lines.append("\n")
        return "\n".join(lines)

    @staticmethod
    def _collect_agent_reviews(record: TriageRecord) -> Dict[str, object]:
        """Extract node-level reviews for one triaged finding."""
        metadata = record.finding.metadata
        return {
            "auditor_review": metadata.get("auditor_review"),
            "skeptic_review": metadata.get("skeptic_review"),
            "judge_review": metadata.get("judge_review"),
        }
